enable_disable_cp:
  description: Enable or disable a charge point
  fields:
    mqtt_prefix:
      name: Prefix for MQTT topic
      description: Prefix on the MQTT server that addresses the respective wallbox
      default: 'openWB/openWB'
      example: 'openWB/openWB'
      required: true
      selector:
        text:
    selected_status:
      name: Charge point status
      description: Desired status of the charge point
      default: 'On'
      required: true
      selector:
        select:
          options:
            - 'On'
            - 'Off'
    charge_point_id:
      name: Charge point ID
      description: ID of the charge point which shall be enabled / disabled
      default: 1
      required: true
      selector:
        number:
          min: 1
          max: 8
change_global_charge_mode:
  description: Change the global charge mode of the wallbox
  fields:
    mqtt_prefix:
      name: Prefix for MQTT topic
      description: respective Prefix on the MQTT server that addresses the respective wallbox
      default: 'openWB/openWB'
      example: 'openWB/openWB'
      required: true    
      selector:
        text:
    global_charge_mode:
      name: Global charge mode
      description: Desired global charge mode
      default: "Sofortladen"
      required: true
      selector:
        select:
          options:
            - "Sofortladen"
            - "Min+PV-Laden"
            - "Nur PV-Laden"
            - "Stop"
            - "Standby"

change_charge_limitation_per_cp:
  description: Change the submode for a charge point in global mode Sofortladen
  fields:
    mqtt_prefix:
      name: Prefix for MQTT topic
      description: respective Prefix on the MQTT server that addresses the respective wallbox
      default: 'openWB/openWB'
      example: 'openWB/openWB'
      required: true
      selector:
        text:
    charge_limitation:
      name: Charge mode
      description: Defines the submode for each charge point in global mode Sofortladen
      default: 'Not limited'
      required: true
      selector:
        select:
          options:
            - 'Not limited'
            - 'kWh'
            - 'SOC'
    charge_point_id:
      name: Charge point ID
      description: ID of the charge point which shall be enabled / disabled
      default: 1
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 8
    energy_to_charge:
      name: Energy to charge in kWhs
      description: Defines the amount of energy to charge in mode Sofortladen
      default: 30
      example: 30
      selector:
        number:
          min: 10
          max: 50
          step: 10         
    required_soc:
      name: Charge upto this SOC
      description: Defines the max SOC to which the vehicle shall be charged in mode Sofortladen
      default: 30
      example: 30
      selector:
        number:
          min: 10
          max: 100
          step: 10

change_charge_current_per_cp:
  description: Change charge current for a charge point
  fields:
    mqtt_prefix:
      name: Prefix for MQTT topic
      description: respective Prefix on the MQTT server that addresses the respective wallbox
      default: 'openWB/openWB'
      example: 'openWB/openWB'
      required: true
      selector:
        text:
    charge_point_id:
      name: Charge point ID
      description: ID of the charge point which shall be enabled / disabled
      default: 1
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 8
    target_current:
      name: Charging current in A
      description: Defines the charging current in A
      default: 6
      example: 6
      selector:
        number:
          min: 6
          max: 16
          step: 1  
enable_disable_price_based_charging:
  description: Enable or disable price-based charging
  fields:
    mqtt_prefix:
      name: Prefix for MQTT topic
      description: Prefix on the MQTT server that addresses the respective wallbox
      default: 'openWB/openWB'
      example: 'openWB/openWB'
      required: true
      selector:
        text:
    selected_status:
      name: Price-based Charging
      description: Desired price-based charging status
      default: 'Off'
      required: true
      selector:
        select:
          options:
            - 'On'
            - 'Off'
    charge_point_id:
      name: Charge point ID
      description: ID of the charge point which shall be enabled / disabled
      default: 1
      required: true
      selector:
        number:
          min: 1
          max: 8
